# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smoothEigensR <- function(persistence, transition, measurement, lagsModelAll, xregModel, obsInSample, hasDelta, xregNumber = 0L, constantRequired = FALSE) {
    .Call('_smooth_smoothEigensR', PACKAGE = 'smooth', persistence, transition, measurement, lagsModelAll, xregModel, obsInSample, hasDelta, xregNumber, constantRequired)
}

hessianCpp <- function(f, x0, h = 1.220703125e-4) {
    .Call('_smooth_hessianCpp', PACKAGE = 'smooth', f, x0, h)
}

matrixPowerWrap <- function(matA, power) {
    .Call('_smooth_matrixPowerWrap', PACKAGE = 'smooth', matA, power)
}

olsCpp <- function(X, y, tol = 1e-7) {
    .Call('_smooth_olsCpp', PACKAGE = 'smooth', X, y, tol)
}

arimaHRCpp <- function(y, arOrders, maOrders, lags, arEstimate, maEstimate, armaParameters, useLevel, bounded) {
    .Call('_smooth_arimaHRCpp', PACKAGE = 'smooth', y, arOrders, maOrders, lags, arEstimate, maEstimate, armaParameters, useLevel, bounded)
}

arimaHRSelectCpp <- function(y, arOrders, maOrders, lags, screen, arMax, maMax, bounded) {
    .Call('_smooth_arimaHRSelectCpp', PACKAGE = 'smooth', y, arOrders, maOrders, lags, screen, arMax, maMax, bounded)
}

arimaParameterBoundsCpp <- function(values, j, sign) {
    .Call('_smooth_arimaParameterBoundsCpp', PACKAGE = 'smooth', values, j, sign)
}

householderQRCpp <- function(X) {
    .Call('_smooth_householderQRCpp', PACKAGE = 'smooth', X)
}

householderCoefCpp <- function(qr, qraux, rDiag, y) {
    .Call('_smooth_householderCoefCpp', PACKAGE = 'smooth', qr, qraux, rDiag, y)
}

householderResidCpp <- function(qr, qraux, rDiag, y) {
    .Call('_smooth_householderResidCpp', PACKAGE = 'smooth', qr, qraux, rDiag, y)
}

forecasterwrap <- function(matvt, matF, matw, h, Etype, Ttype, Stype, lagsModel, matxt, matat, matFX) {
    .Call('_smooth_forecasterwrap', PACKAGE = 'smooth', matvt, matF, matw, h, Etype, Ttype, Stype, lagsModel, matxt, matat, matFX)
}

